export const
  VIEW_READY = 'VIEW_READY',
  TOGGLE_LOCATE = 'TOGGLE_LOCATE',
  TOGGLE_SHARE = 'TOGGLE_SHARE',
  FETCH_ITEM_INFO = 'FETCH_ITEM_INFO',
  EARTHQUAKE_FILTER_UPDATED = 'EARTHQUAKE_FILTER_UPDATED',
  WATER_FILTER_UPDATED = 'WATER_FILTER_UPDATED';
